const createConstants = (...constants) => {
  let types = {};
  for(let type of constants){
    types[type] = type;
  }
  return types;
};

export default createConstants(
    'USER_LOGIN_REQUEST',
    'USER_LOGIN_SUCCESS',
    'USER_LOGIN_FAILURE',
    'USER_LOGIN_FINISH',

    'USER_SIGNUP_REQUEST',
    'USER_SIGNUP_SUCCESS',
    'USER_SIGNUP_FAILURE',
    'USER_SIGNUP_FINISH',

    'SIGNUP_CAP_REQUEST',
    'SIGNUP_CAP_SUCCESS',
    'SIGNUP_CAP_FAILURE',

    'COMPANY_LIST_REQUEST',
    'COMPANY_LIST_SUCCESS',
    'COMPANY_LIST_FAILURE',

    'POSITION_LIST_REQUEST',
    'POSITION_LIST_SUCCESS',
    'POSITION_LIST_FAILURE',

    'COMPANY_DETAIL_REQUEST',
    'COMPANY_DETAIL_SUCCESS',
    'COMPANY_DETAIL_FAILURE',

    'JOB_DETAIL_REQUEST',
    'JOB_DETAIL_SUCCESS',
    'JOB_DETAIL_FAILURE',

    'PROFILE_INFO_REQUEST',
    'PROFILE_INFO_SUCCESS',
    'PROFILE_INFO_FAILURE',

    'PROFILE_INFOPOST_REQUEST',
    'PROFILE_INFOPOST_SUCCESS',
    'PROFILE_INFOPOST_FAILURE',

    'PROFILE_RESUME_REQUEST',
    'PROFILE_RESUME_SUCCESS',
    'PROFILE_RESUME_POST',
    'PROFILE_RESUME_POST_SUCCESS',
    'PROFILE_RESUME_REFRESH',

    'PROFILE_WORK_REQUEST',
    'PROFILE_WORK_SUCCESS',
    'PROFILE_WORK_FAILURE',

    'PROFILE_WORKPOST_REQUEST',
    'PROFILE_WORKPOST_SUCCESS',

    'CUSTOMEJOB_LIST_REQUEST',
    'CUSTOMEJOB_LIST_SUCCESS',
    'CUSTOMEJOB_LIST_FAILURE',

    'PROFILE_EDU_REQUEST',
    'PROFILE_EDU_SUCCESS',
    'PROFILE_EDU_FAILURE',

    'PROFILE_EDUPOST_REQUEST',
    'PROFILE_EDUPOST_SUCCESS',

    'CUSTOMEORGANIZATIONS_LIST_REQUEST',
    'CUSTOMEORGANIZATIONS_LIST_SUCCESS',
    'CUSTOMEORGANIZATIONS_LIST_FAILURE',

    'CUSTOMEORGANIZATIONS_TIME_ORDER',
    'CUSTOMEORGANIZATIONS_HOT_ORDER',
    'CUSTOMEORGANIZATIONS_LENGTH_ORDER',

    'CUSTOMEJOBS_TIME_ORDER',
    'CUSTOMEJOBS_HOT_ORDER',


    'IS_LAUDED_REQUEST',
    'IS_COLLECTED_REQUEST',

    'INTERNAL_SERVER_ERROR',
);