const createConstants = (...constants) => {
  let types = {};
  for(let type of constants){
    types[type] = type;
  }
  return types;
};

export default createConstants(
    'USER_LOGIN_REQUEST',
    'USER_LOGIN_SUCCESS',
    'USER_LOGIN_FAILURE',
    'USER_LOGIN_FINISH',

    'USER_SIGNUP_REQUEST',
    'USER_SIGNUP_SUCCESS',
    'USER_SIGNUP_FAILURE',
    'USER_SIGNUP_FINISH',

    'SIGNUP_CAP_REQUEST',
    'SIGNUP_CAP_SUCCESS',
    'SIGNUP_CAP_FAILURE',

    'COMPANY_LIST_REQUEST',
    'COMPANY_LIST_SUCCESS',
    'COMPANY_LIST_FAILURE',

    'POSITION_LIST_REQUEST',
    'POSITION_LIST_SUCCESS',
    'POSITION_LIST_FAILURE',

    'COMPANY_DETAIL_REQUEST',
    'COMPANY_DETAIL_SUCCESS',
    'COMPANY_DETAIL_FAILURE',

    'JOB_DETAIL_REQUEST',
    'JOB_DETAIL_SUCCESS',
    'JOB_DETAIL_FAILURE',

    'PROFILE_INFO_REQUEST',
    'PROFILE_INFO_SUCCESS',
    'PROFILE_INFO_FAILURE',

    'INTERNAL_SERVER_ERROR',
);