# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
