# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleData', '0002_auto_20171123_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='onceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('user_pwd', models.CharField(max_length=32)),
                ('user_sex', models.CharField(max_length=4)),
                ('user_email', models.CharField(max_length=256)),
                ('user_phone', models.CharField(max_length=256)),
                ('user_address', models.CharField(max_length=256)),
                ('user_city', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
