# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleData', '0003_auto_20171123_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onceuser',
            name='user_address',
            field=models.CharField(blank='true', max_length=256),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_city',
            field=models.CharField(blank='true', max_length=256),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_email',
            field=models.CharField(blank='true', max_length=256),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_name',
            field=models.CharField(blank='false', max_length=16),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_phone',
            field=models.CharField(blank='true', max_length=256),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_pwd',
            field=models.CharField(blank='false', max_length=32),
        ),
        migrations.AlterField(
            model_name='onceuser',
            name='user_sex',
            field=models.CharField(blank='true', max_length=4),
        ),
    ]
